name: Build and Test on Windows
on: [push]
jobs:
  windows:
    defaults:
      run:
        shell: cmd
    strategy:
      matrix:
          version: ["7.4"]
          arch: [x64,x86]
          ts: [ts]
    runs-on: windows-2019
    steps:
      - name: Checkout memcached
        uses: actions/checkout@v2
        with:
          repository: php-memcached-dev/php-memcached
      - name: Download memcached.exe
        run: |
          curl -L http://static.runoob.com/download/memcached-1.4.5-amd64.zip -o memcached.zip
          7z x memcached.zip -o.\mem
          mem\memcached-amd64\memcached.exe -d
      - name: Setup PHP
        id: setup-php
        uses: cmb69/setup-php-sdk@v0.3
        with:
          version: ${{matrix.version}}
          arch: ${{matrix.arch}}
          ts: ${{matrix.ts}}
          deps: zlib
      - name: Download deps
        run: |
          curl -L https://github.com/lifenglsf/libmemcached-window-dll-lib/blob/main/${{matrix.arch}}.zip?raw=true -o ${{matrix.arch}}.zip
          7z x ${{matrix.arch}}.zip -o..\deps
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
          toolset: ${{steps.setup-php.outputs.toolset}}
      - name: phpize
        run: phpize
      - name: configure
        run: configure --enable-memcached=shared --enable-memcached-session --enable-memcached-json --with-php-build=..\deps --with-prefix=${{steps.setup-php.outputs.prefix}} --with-config-file-path=${{steps.setup-php.outputs.prefix}}
      - name: make
        run: nmake
      #- name: show file
      #  run: dir x64 /N /S
      - name: make install
        run: nmake install
     
      - name: copy ini
        run: copy ${{steps.setup-php.outputs.prefix}}\php.ini-development ${{steps.setup-php.outputs.prefix}}\php.ini
      - name: copy libmemcached 
        run:  copy ..\deps\bin\libmemcached.dll ${{steps.setup-php.outputs.prefix}}
      - name: set extension dir
        run : echo extension_dir="${{steps.setup-php.outputs.prefix}}\ext"; >>${{steps.setup-php.outputs.prefix}}\php.ini
      - name: show file
        run: dir ${{steps.setup-php.outputs.prefix}} /N /S
      - name: extension path
        run: php -i|grep "extension_dir"
      - name: add memcached ext
        run : echo extension=memcached; >>${{steps.setup-php.outputs.prefix}}\php.ini
      - name: show ini config
        run: php --ini
      - name: php module
        run: php -m
     # - name: test
     #   run: |
          #rm run-test.php
          #curl -L https://raw.githubusercontent.com/lifenglsf/libmemcached-window-dll-lib/main/run-tests.php -o run-tests.php
          #php run-tests.php --show-diff -g FAIL,BORK,WARN,LEAK tests/*.phpt
      - name: create zip
        run: |
          zip -r ${{steps.setup-php.outputs.prefix}}/php-7.4-x64.zip ${{steps.setup-php.outputs.prefix}}/libmemcached.dll ${{steps.setup-php.outputs.prefix}}/ext/php_memcached.dll
          
      - name: delete_tag
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true # default: false
          tag_name: latest # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{steps.setup-php.outputs.prefix}}/libmemcached.dll,${{steps.setup-php.outputs.prefix}}/ext/php_memcached.dll,${{steps.setup-php.outputs.prefix}}/php-7.4-x64.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          tag: latest
      #- name: test
      #  run: php -r "print_r(new Memcached());"
        
